version: '3.8'

services:
  postgres:
    image: postgres:13.3-alpine
    container_name: postgres-produtos
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=techfood-produtos
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./src/main/resources/sql_scripts/:/docker-entrypoint-initdb.d

  app:
    container_name: techfood-produtos-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/techfood-produtos
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres