server:
  port: 8080

spring:
  application:
    name: techfood-produtos

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/techfood-produtos
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

