apiVersion: v1
kind: Service
metadata:
  name: techfood-produtos-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  selector:
    app: techfood-produtos-app
