apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: techfood-app-hpa
  namespace: techfood-produtos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techfood-produtos-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
